{
 "title": "Main Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}